# Generated by Django 5.2.6 on 2025-12-26 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_type', models.IntegerField(choices=[(1, 'Sport'), (2, 'Mountain'), (3, 'Town'), (4, 'Light')], default=4)),
                ('image_path', models.ImageField(upload_to='images')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField(max_length=1024)),
                ('price', models.IntegerField(default=None)),
                ('is_there_any', models.BooleanField(default=False)),
                ('bike_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_descripton', models.TextField(max_length=1366)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BW.bikes')),
            ],
        ),
    ]
